import { ScrollView,StyleSheet,Text,Pressable,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Brain,Wind,Lightbulb,Moon,ShieldAlert,Activity,Sparkles,ArrowUpRight } from 'lucide-react-native';
import { AmbientBackground,GlassCard,GlowOrb,P,Reveal } from '@/components/PremiumUI';
const TOOLS=[
 {title:'AI Voice Therapist',sub:'Live voice session with Dr. Maya',icon:Sparkles,c:P.purple,route:'/therapist'},
 {title:'Wellness Assessment',sub:'Understand your patterns',icon:Brain,c:P.cyan,route:'/assessment'},
 {title:'Guided Breathing',sub:'Regulate your pace',icon:Wind,c:P.mint,route:'/breathe'},
 {title:'Sleep Reset',sub:'Wind down with intention',icon:Moon,c:P.pink,route:'/breathe'},
 {title:'Daily Tips',sub:'Small practical support',icon:Lightbulb,c:P.gold,route:'/tips'},
 {title:'Emergency Support',sub:'Find immediate resources',icon:ShieldAlert,c:P.danger,route:'/tips'},
 {title:'Progress & Insights',sub:'See your wellness signals',icon:Activity,c:P.mint,route:'/assessment'},
];
export default function ToolsScreen(){const r=useRouter();return <AmbientBackground><SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">
 <Reveal><View style={styles.hero}><View style={{flex:1}}><Text style={styles.kicker}>YOUR TOOLKIT</Text><Text style={styles.title}>Tools that meet you where you are.</Text><Text style={styles.sub}>No checklist. Pick the experience that fits this moment.</Text></View><GlowOrb size={90}/></View></Reveal>
 <Reveal delay={100}><GlassCard glow style={styles.ai}><View style={styles.aiIcon}><Sparkles size={19} color={P.white}/></View><View style={{flex:1}}><Text style={styles.aiKicker}>PERSONALIZED</Text><Text style={styles.aiTitle}>Your next useful step</Text><Text style={styles.aiSub}>Start with a mood check-in, then let Mindspace guide what comes next.</Text></View></GlassCard></Reveal>
 <Text style={styles.section}>EXPLORE</Text><View style={styles.grid}>{TOOLS.map((t,i)=>{const I=t.icon;return <Reveal key={t.title} delay={160+i*45} style={styles.wrap}><Pressable onPress={()=>r.push(t.route as any)} style={({pressed})=>[styles.tile,pressed&&{transform:[{scale:.97}]}]}><View style={[styles.icon,{backgroundColor:`${t.c}18`,shadowColor:t.c}]}><I size={22} color={t.c}/></View><Text style={styles.tileTitle}>{t.title}</Text><Text style={styles.tileSub}>{t.sub}</Text><ArrowUpRight size={16} color={t.c} style={styles.arrow}/></Pressable></Reveal>})}</View>
 <Reveal delay={500}><GlassCard style={{marginTop:14}}><View style={styles.private}><View style={styles.shield}><ShieldAlert size={18} color={P.mint}/></View><View style={{flex:1}}><Text style={styles.privateTitle}>Support when it matters.</Text><Text style={styles.privateText}>If you feel unsafe or in immediate danger, contact local emergency services or a trusted person.</Text></View></View></GlassCard></Reveal>
 <View style={{height:100}}/>
 </ScrollView></SafeAreaView></AmbientBackground>}
const styles=StyleSheet.create({safe:{flex:1},scroll:{padding:18,paddingBottom:100},hero:{padding:20,borderRadius:28,borderWidth:1,borderColor:'rgba(139,92,246,.28)',backgroundColor:'rgba(16,15,32,.88)',flexDirection:'row',alignItems:'center',overflow:'hidden'},kicker:{color:'#BFAEFF',fontSize:10,letterSpacing:1.8,fontFamily:'Inter-Bold'},title:{color:P.white,fontSize:28,lineHeight:34,fontFamily:'Inter-ExtraBold',marginTop:5,maxWidth:280},sub:{color:P.muted,fontSize:12.5,lineHeight:19,fontFamily:'Inter-Regular',marginTop:7,maxWidth:290},ai:{marginTop:12,flexDirection:'row',gap:12,alignItems:'center'},aiIcon:{width:42,height:42,borderRadius:14,backgroundColor:P.violet,alignItems:'center',justifyContent:'center'},aiKicker:{color:P.purple,fontSize:9,letterSpacing:1.4,fontFamily:'Inter-Bold'},aiTitle:{color:P.white,fontSize:15,fontFamily:'Inter-Bold',marginTop:2},aiSub:{color:P.muted,fontSize:11.5,lineHeight:17,marginTop:3,fontFamily:'Inter-Regular'},section:{color:P.muted,fontSize:10,letterSpacing:1.7,fontFamily:'Inter-Bold',marginTop:25,marginBottom:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},wrap:{width:'48%'},tile:{height:160,borderRadius:23,borderWidth:1,borderColor:P.line,backgroundColor:'rgba(16,19,34,.78)',padding:14},icon:{width:46,height:46,borderRadius:15,alignItems:'center',justifyContent:'center',shadowOpacity:.4,shadowRadius:15},tileTitle:{color:P.white,fontSize:14,fontFamily:'Inter-Bold',marginTop:18},tileSub:{color:P.muted,fontSize:10.5,lineHeight:16,fontFamily:'Inter-Regular',marginTop:4,maxWidth:125},arrow:{position:'absolute',right:14,bottom:14},private:{flexDirection:'row',gap:12,alignItems:'center'},shield:{width:42,height:42,borderRadius:14,backgroundColor:'rgba(77,224,178,.1)',alignItems:'center',justifyContent:'center'},privateTitle:{color:P.white,fontSize:14,fontFamily:'Inter-Bold'},privateText:{color:P.muted,fontSize:11.5,lineHeight:17,fontFamily:'Inter-Regular',marginTop:4}});
